version: '2.1'

networks:
  servers:

services:

  balancer:
    build: architecture-practice-4-template
    command: "lb"
    networks:
      - servers
    ports:
      - "8090:8090"

  server1:
    build: architecture-practice-4-template
    networks:
      - servers
    ports:
      - "8080:8080"

  server2:
    build: architecture-practice-4-template
    networks:
      - servers
    ports:
      - "8081:8080"

  server3:
    build: architecture-practice-4-template
    networks:
      - servers
    ports:
      - "8082:8080"
